services:
  traefik:
    image: traefik:v3.6.0
    restart: unless-stopped
    networks:
      - n8n_service
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: unless-stopped
    volumes:
      - n8n_data:/home/node/.n8n
    labels:
      - traefik.enable=true
      - "traefik.http.routers.n8n.rule=Host(`${N8N_DOMAIN_NAME}`)"
      - traefik.http.routers.n8n.entrypoints.0=websecure
      - traefik.http.routers.n8n.entrypoints.1=web
      # - traefik.http.services.n8n.loadbalancer.servers.0.url=http://localhost:5678
    expose:
      - 5678
    networks:
      - n8n_service
    depends_on:
      - traefik

networks:
  n8n_service: 
    driver: bridge
    
volumes:
  n8n_data: 