services:
  traefik:
    image: traefik:v3.6.0
    restart: unless-stopped
    networks:
      - n8n_service
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_data:/letsencrypt
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: unless-stopped
    environment:
      - N8N_HOST=${N8N_DOMAIN_NAME}
      - N8N_PROTOCOL=https
      - N8N_PORT=5678
      - NODE_ENV=production
      - WEBHOOK_URL=https://${N8N_DOMAIN_NAME}/
      - N8N_PROXY_HOPS=1
    ports:
      - 5678:5678
    volumes:
      - n8n_data:/home/node/.n8n
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`${N8N_DOMAIN_NAME}`)"
      - "traefik.http.routers.n8n.entrypoints=websecure"
      - "traefik.http.routers.n8n.tls=true"
      - "traefik.http.routers.n8n.tls.certResolver=letsencrypt"
    expose:
      - 5678
    networks:
      - n8n_service
    depends_on:
      - traefik

networks:
  n8n_service: 
    driver: bridge
    
volumes:
  n8n_data: 
  traefik_data: 